Readme compliancy
codenco-dev/print-factory pull request #1
Opened 2023-02-04 16:26 UTC by tyteck

## readme-compliancy

`--inline` mode
`--force` mode

standard mode is creating `app/Printable/MyExample.php` and `resources/views/my-example.blade.php`.
the view is using namespaced print layout (included in package).

2023-02-04 20:39 UTC, thomasdominic requested changes
Beaucoup mieux, colle beaucoup plus avec ce que j'attendais

2023-02-04 20:39 UTC, thomasdominic commented on src/Commands/PrintableClass.stub
> +        $this->setPdfFileName('{{kebab}}.pdf');
**suggestion \[blocking]:** Je pense que tout ca, le constructeur, peut être dans le Contrat et que tu n'as besoin, ici, que d'une méthode render() qui retourne le contenu de la vue.
Et cette méthode render, tu l'appel comme ca 
```
        $this->setHtmlContent($this->render());
        $this->setPdfFileName('{{kebab}}.pdf');
```

2023-02-04 20:39 UTC, thomasdominic commented on src/Commands/PrintableClass.stub
> +        $this->setPdfFileName('{{kebab}}.pdf');
Comme ca, tu auras juste une méthode render()  base dans un simple printable

Et dans un printable "invoice", tu auras les méthodes métiers headerFrom, headerTo, Footer et lines et c'est tout.

2023-02-06 17:11 UTC, tyteck commented on src/Commands/PrintableClass.stub
> +        $this->setPdfFileName('{{kebab}}.pdf');
:thinking: bah ... tu ne peux pas mettre `$this->setPdfFileName('{{kebab}}.pdf');` dans le contrat ... je crois voir ce que tu veux

2023-02-13 13:46 UTC, thomasdominic requested changes

2023-02-13 13:46 UTC, thomasdominic commented on src/Commands/PrintableClass.stub
> +    protected string $pdfFileName = '{{kebab}}.pdf';
🚫 **issue:** Y'a juste cela, j'aurai fait autrement, une méthode, dans la classe abstraite, que tu peux, au pire redéfinir, mais si tu t'en fou, tu as même pas à le voir.
Elle retourne quoi ? Un truc du genre
return 'file'.now()->format('YmdHis').pdf

2023-02-13 13:46 UTC, thomasdominic commented on src/Commands/PrintableClass.stub
> +    public function render(): string
👏**praise**: 👍

2023-02-13 13:46 UTC, thomasdominic commented on src/Commands/PrintableClass.stub
> +    protected string $pdfFileName = '{{kebab}}.pdf';
```
public string $name = 'pdfFile';

public function getFilename()
    {
        return once(function () {
            return $this->buildFilename();
        });
    }

protected function buildFilename()
    {
        return $this->name.now()->format('ymd-his').'.csv';
    }

public function __construct()
    {
        $this->setHtmlContent($this->render());
        $this->setPdfFileName($this->getFilename());
}
```

voila à la grosse comment je ferai.

2023-02-13 13:46 UTC, thomasdominic commented on src/Contracts/Printable.php
> +        $this->setPdfFileName($this->pdfFileName);
voir plus haut

2023-02-13 13:46 UTC, thomasdominic commented on src/Commands/PrintableClass.stub
> +    protected string $pdfFileName = '{{kebab}}.pdf';
Et pourquoi je le mets dans une méthode et pas dans une variable, cela permet facilement de dynamiser ton nom dans ta classe enfant, car si tu veux mettre, par exemple la date, ca va se compliqué avec la propriété.

2023-02-14 17:30 UTC, tyteck commented on src/Commands/PrintableClass.stub
> +    protected string $pdfFileName = '{{kebab}}.pdf';
oki

2023-02-15 13:10 UTC, thomasdominic approved these changes

2023-02-18 11:05 UTC, merged